### ISSUE TITLE
Metadata Sidebar or Modal

### ISSUE THREAD

**Issue by hmtinc** [PathwayCommons/pathways-search#148]
# Expansion of Tooltip Metadata

The tooltip ideally will only provide a few details regarding the the states and other variables, but the biopax file contains alot more metadata. This data should be represented in either a sidebar or popup modal which provides an interactive display of information. 

Ideally the information displayed would be similar to the data available through PCViz (i.e http://www.pathwaycommons.org/pcviz/#pathsbetween/MDM2,TP53,BAX), but implemented along side the SBGN based viewer.

**Comment by jvwong** [comment]
Rather than PCViz ('ball-and-stick'), the best model is [ChiBE](https://github.com/PathwayCommons/chibe) desktop software that directly loads and processes BioPAX to render SBGN-PD

e.g. [Signalling by BMP (Reactome)](http://www.reactome.org/PathwayBrowser/#/R-HSA-201451)

- [BioPAX](http://www.pathwaycommons.org/pc2/get?uri=http://identifiers.org/reactome/R-HSA-201451)
- [Search app](http://www.pathwaycommons.org/pathways/#/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-201451)

ChiBE view:

![screenshot at sep 27 09-47-17](https://user-images.githubusercontent.com/4706307/30917004-e075260c-a368-11e7-861f-034fe0df9804.png)

**Comment by IgorRodchenkov** [comment]
Done in the app-ui repo.
