### ISSUE TITLE
Back button highlights multiple pages

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#24]
The use of the back button on a page >1 leads to multiple pages selected in pagination bar.

e.g. case - Select '2' then back button. 

![search_pagination_break](https://cloud.githubusercontent.com/assets/4706307/23026046/04eabfb4-f42e-11e6-912e-466409868cda.png)

**Comment by mj3cheun** [comment]
Took a look. I can see the problem in my own browser, but if you click anywhere else on the page, the extra selected button disappears. Also, the pagination implementation is done by Bootstrap, not by me, so any fix will not be clean. However, if this bug is really an issue, I am sure I can hack a fix in.

**Comment by jvwong** [comment]
Agreed to remove pagination altogether
