### ISSUE TITLE
Search Options tooltip text

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#30]
Suggest text:

-- begin

This menu provides a way to refine your search results. For example, filter the results by database or order by pathway size.   

-- end

I am assuming this is applied after a query is submitted (right?). Are we providing a reorder by size option?

**Comment by mj3cheun** [comment]
I am thinking about leaving out the reorder by size because I don't really see how its helpful.

So for filtering results by database, it will run the search query again with the filter in order to fetch new results. If I was to implement reorder by size, it will be applied to either the existing list or to any list generated in the future.

**Comment by jvwong** [comment]
If size filtering is handled wisely,  I could be convinced to punt order by size. 
 
Will this handle the edge case where I set filters before submit? Will the menu reflect this state?

**Comment by mj3cheun** [comment]
Again, with the beta, since we can filter by number of items, thinking of pushing pathways with around < 4 and > 200 nodes to the bottom.

Yes I haven't written anything for this yet, but if you set filters before submitting, it will do a search, say no results found, and then if you press search button everything will proceed as normal. You can try the datasource filtering on the github prototype.

**Comment by jvwong** [comment]
let's make sure we filter out massive pathways (e.g. >500)?

**Comment by jvwong** [comment]
Closing and reopen the latter issue.
