### ISSUE TITLE
Unable to search: 'Notch Delta' 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#54]
Breaking case:  Able to search for "Notch" and "Delta" but app breaks with "Notch Delta"

![screenshot at apr 07 16-42-42](https://cloud.githubusercontent.com/assets/4706307/24819123/55b8be64-1bb1-11e7-908d-254ce1d441fe.png)

**Comment by mj3cheun** [comment]
This is expected behaviour. The search looks for the intersection of all the words you type in, in this case in the name. If the dataset of one word does not intersect with the dataset of the other word, you get no results.

**Comment by jvwong** [comment]
The UI indicates nothing is happening so I had to open the console.

Not getting a result for 'Notch Delta' sounds very scary to me.

**Comment by mj3cheun** [comment]
Yes, the UI not responding is a known bug documented here: https://github.com/PathwayCommons/pathways-search/issues/55.

As for "notch delta" not returning, unfortunately that seems to be a consequence of looking only in name, which is unlikely to contain the participant names unless the pathway is named for it.

Contrast the following...
Enhance disabled
http://localhost:8080/#/search?enhance=false&gt=3&lt=200&q=notch%20delta&type=Pathway
Enhance enabled
http://localhost:8080/#/search?enhance=true&gt=3&lt=200&q=notch%20delta&type=Pathway

You will notice that if you search through the enhance disabled search results, delta is not in the display name anywhere. Not certain what the right solution is here since the enhanced search works really well for looking up pathway names in general.
