### ISSUE TITLE
Show pathway 'name' on view pane

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#8]
The view pane should reproduce the search result 'name' or 'title' that was selected in order to provide an explicit link between the two.

**Comment by mj3cheun** [comment]
This is slightly complicated problem for a few reasons. When, I go to a pathway URL, lets say this one: http://mj3cheun.github.io/pathways-search.html#/pathway?uri=http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_1d99625aa7f8f4a3f3189e8b237522c3, I make the call to get the SBGNML, which does not contain the name, therefore I do not automatically have the information I need to display the name.

There are two ways I can think of to get the name. One is to link the pathway to the search result, which I am reluctant to do because there are a load of drawbacks to doing this, including no longer being able to open a pathway by URL has I have done above. Note that this is the way Igor has chosen to do it in the prototype. The second is to attach the name to the URL of the pathway as well as the URI, which can get messy in the long run.

I think I will need to think on this one further, and maybe talk to Igor.

**Comment by jvwong** [comment]
This is a client-side concern as the browser has the SearchHit. Is there no way for ReactJS to pass this info to another component? I'm thinking this is a must-have.

**Comment by mj3cheun** [comment]
No there definitely is, I just feel its a bit iffy code-hygeine wise and not something I particularly want to do. However if its the only option (nothing can be done server side) then it can easily be implemented.

**Comment by jvwong** [comment]
What about passing in a ['state'](https://github.com/ReactTraining/react-router/blob/389df9c0ba603b758de4a979a34ee10276f9a8d0/docs/API.md#link) key/value to the [Link](https://github.com/mj3cheun/pathways-search/blob/7a6e95f0c62bb4f379a287822c9a753cbfc88104/js/search/components/SearchItem.jsx#L12)?

**Comment by mj3cheun** [comment]
Fixed in commit bd4ef4122dcee01b19a21aa45139f5dd1aa1d9f7. Added name to Pathway page.

Passing the 'state' key/value to the link is essentially the same as linking the pathway to the search result, and will result in the drawbacks described above, mainly not being able to pass the URL of the pathway as a standalone link. I have chosen to instead place all required information in the URL itself. Please see commit for implementation details. Originally, I didn't want to do this because it is further cluttering the URL but I still feel this is the best possible solution.
