### ISSUE TITLE
Increase node label font

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#99]
There has been the observation that viewing node labels was difficult. Suggest to increase label font-size. 

Alternative strategies for viewing at low zoom
  - Navigator or 'birds eye view' : https://github.com/cytoscape/cytoscape.js-navigator
  - Fish-eye?

**Comment by d2fong** [comment]
- on hover --> increase font, node width, and node height based on how large the graph is

scale node w / h based on:
* the ratio of w / h it currently has
* how many nodes are in the graph (smaller graphs, scale the nodes less, scale the text less)
* how large the graph is (probably has some cytoscape api call like ```cy.extent()```

**Comment by maxkfranz** [comment]
@d2fong You could scale such that the rendered font size is always the same so you get some consistency.  E.g. `size = defaultRenderedSize / currentZoom`.  Maybe `size = max( size, 2 )` too so you guarantee a minimum factor increase.

If you do something like graph size, you'll get inconsistent results.

**Comment by d2fong** [comment]
@maxkfranz Okay, I will try that. Thanks.

**Comment by d2fong** [comment]
## Todo

#### Reduce hover style effect for small graphs;

In small graphs we run cose-bilkent on them which causes nodes to be tightly packed in together.  Coupled with long labels, increasing the label size will cause more harm than good.

#### Increase node size / edge width of the currently hovered node

Because nodes look so similar, this will give users another visual cue as to where their cursor is in the graph.

#### Improve the default label style

Label readability can further be improved by increasing the font size, and adding a white outline.

#### Turn this into an extension

Hover seems to add a nice bit of interaction to the graph, so it might be worth it to generalize this into an extension.

**Comment by d2fong** [comment]
### idea
- animate zoom in on mouseover before applying styles
- animate zoom out on mouseout

**Comment by jvwong** [comment]
Can we close? I think this is done as of c23276820dd24ef05114ee602e696942716f218f

**Comment by d2fong** [comment]
Yeah I think so
